{
 "title": "Content_Repository",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "General Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Project Community",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_contributors{exported_job=~\".*\"})",
       "legendFormat": "Contributors"
      },
      {
       "expr": "sum(ComplianceAsCode_content_subscribers_count{exported_job=~\".*\"})",
       "legendFormat": "Subscribers"
      },
      {
       "expr": "sum(ComplianceAsCode_org_team_size{exported_job=~\".*\"})",
       "legendFormat": "Team Size"
      },
      {
       "expr": "sum(ComplianceAsCode_org_members{exported_job=~\".*\"})",
       "legendFormat": "Org Members"
      },
      {
       "expr": "sum(ComplianceAsCode_org_admins{exported_job=~\".*\"})",
       "legendFormat": "Org Admins"
      }
     ]
    },
    {
     "title": "Project Popularity",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_stargazers_count{exported_job=~\".*\"})",
       "legendFormat": "Stars"
      },
      {
       "expr": "sum(ComplianceAsCode_content_forks_count{exported_job=~\".*\"})",
       "legendFormat": "Forks"
      },
      {
       "expr": "sum(ComplianceAsCode_content_subscribers_count{exported_job=~\".*\"})",
       "legendFormat": "Subscribers"
      }
     ]
    },
    {
     "title": "Project Labels",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_labels_count{exported_job=~\".*\"})",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "Quick Links",
     "type": "text",
     "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
     "options": {
      "content": "* <a href=\"https://github.com/ComplianceAsCode/content\" target=\"_blank\">Code</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/issues\" target=\"_blank\">Issues</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/pulls\" target=\"_blank\">Pull requests</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/discussions\" target=\"_blank\">Discussions</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/actions\" target=\"_blank\">Actions</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/pulse\" target=\"_blank\">Insights</a>\n\n"
     }
    },
    {
     "title": "Org Repos",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_org_repositories{exported_job=~\".*\"})",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "Org Team",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_org_team_size{exported_job=~\".*\"})",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "Project Events (activity)",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_events{exported_job=~\".*\"})",
       "legendFormat": "Number of Events"
      }
     ]
    }
   ]
  },
  { "title": "Repository PRs Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Open PRs Summary",
   "type": "timeseries",
   "description": "This chart shows the main metrics about Open PRs.\n\nWhen comparing the numbers within an interval it is interesting to check the \"Difference\" value. Negative values are usually good and mean the queue is getting smaller in the specific interval. Positive values may indicate that PRs are taking too long to be reviewed and merged or the community is getting more active.",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Open PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Unassigned PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Outdated PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Draft PRs"
    }
   ]
  },
  {
   "title": "PRs Activity",
   "type": "piechart",
   "description": "This pie chat shows the distribution of Active and Inactive PRs, which are PRs without updates within the last 15 days.\n\nIn general it is not good to have Inactive PRs in the project. Maintainers should check them. It is possible that a contributor is waiting for a feedback or an unsolved discussion needs intervention and final decision from a maintainer.\n\nThe Draft PRs are not considered Inactive PRs in this context because they are usually expected to be outdated. It is a common practice that authors set their PRs to draft when something is still pending but the author does not expected to work on it soon.",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"}))",
     "legendFormat": "Active PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Inactive PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Draft PRs"
    }
   ]
  },
  {
   "title": "Team PRs Activity",
   "type": "piechart",
   "description": "This pie chat shows the distribution of Active and Inactive PRs filed by Team members, including eventual Draft PRs. Inactive PRs are PRs without updates within the last 15 days.\n\nPing a colleague if your PR is too long waiting review. If you have an inactive Draft PR, consider to close it or to provide a short update about your plans to work on it.",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_old_open_pulls_team{exported_job=~\".*\"})",
     "legendFormat": "Active PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_old_open_pulls_team{exported_job=~\".*\"})",
     "legendFormat": "Inactive PRs"
    }
   ]
  },
  {
   "title": "PRs Source",
   "type": "piechart",
   "description": "This pie chart shows how the Open PRs are distributed based on authors.\n\nThese metrics are good to better understand how balanced are the collaboration in the project. But they should not be analysed alone.\n\nIn general, all team members are also project maintainers. So it is natural to have more collaboration among team members reflecting in better quality code and consequently faster reviews. Therefore, it is expected that most of the Open PRs comes from the Community.\n\nThese number can be better contextualized by analyzing the other charts, specially the ones about Products and Standards distribuition.",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"})",
     "legendFormat": "Team"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"})",
     "legendFormat": "Community"
    }
   ]
  },
  {
   "title": "PRs Lifetime Average",
   "type": "timeseries",
   "description": "This chart shows the lifetime average of Open PRs but also provides the same metric for closed PRs within the last 30 and 90 days.\n\nIt is usually not good when the Open PRs lifetime average increases. It may indicate that more attention is needed from maintainers in order to review open PRs and allow the authors to move forward. The context should be clarified.\n\nIt is good to compare the lifetime of Open PRs with closed PRs within the last 30 and 90 days to find patterns and trends. Ideally, the three metrics should have similar and small values.",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_lifetime_average{exported_job=~\".*\"})",
     "legendFormat": "Open PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_closed_pulls_lifetime_average_30days{exported_job=~\".*\"})",
     "legendFormat": "Closed PRs (30d)"
    },
    {
     "expr": "sum(ComplianceAsCode_content_closed_pulls_lifetime_average_90days{exported_job=~\".*\"})",
     "legendFormat": "Closed PRs (90d)"
    }
   ]
  },
  {
   "title": "PRs Assigning Rate",
   "type": "piechart",
   "description": "This pie chat shows the distribution of Assigned and Unassigned PRs, except for Draft PRs.\n\nIn general it is not good to have many Unassigned PRs in the project. Maintainers should assign themselves to Unassigned PRs or delegate an assignee to review and allow the PR to move forward.\n\nIf you are not comfortable to assign the PR for yourself or delegate an assignee, you can still help by triaging the PR and including proper labels. It will make it easier to other maintainers to collaborate.\n\nThe Draft PRs are not considered Inactive PRs in this context because they are usually not expecting reviews.",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"}))",
     "legendFormat": "Assigned"
    },
    {
     "expr": "sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Unassigned"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Draft PRs"
    }
   ]
  },
  {
   "title": "Team PRs Assigning Rate",
   "type": "piechart",
   "description": "This pie chat shows the distribution of Assigned and Unassigned PRs filed by Team members, including eventual Draft PRs.\n\nIn general it is not good to have many Unassigned PRs in the project. Be nice with your colleagues and assign yourself to their Unassigned PRs and help to sucessfully finish it.\n\nIf you are not comfortable to assign the PR for yourself or delegate an assignee, you can still help by triaging the PR and including proper labels. It will make it easier to other maintainers to collaborate.",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_unassigned_open_pulls_team{exported_job=~\".*\"})",
     "legendFormat": "Assigned"
    },
    {
     "expr": "sum(ComplianceAsCode_content_unassigned_open_pulls_team{exported_job=~\".*\"})",
     "legendFormat": "Unassigned"
    }
   ]
  },
  {
   "title": "Repository Issues Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Issues Summary",
     "type": "timeseries",
     "description": "This chart shows the main metrics about Open Issues.\n\nWhen comparing the numbers within an interval it is interesting to check the \"Difference\" value. Negative values are usually good and mean the queue is getting smaller in the specific interval. Positive values may indicate that Issues are taking too long to be reviewed and resolved.\n\nPeaks might also indicate more serious issues in a specific release or profile.",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})",
       "legendFormat": "Open Issues"
      },
      {
       "expr": "sum(ComplianceAsCode_content_unassigned_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"})",
       "legendFormat": "Unassigned Issues"
      },
      {
       "expr": "sum(ComplianceAsCode_content_old_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"})",
       "legendFormat": "Outdated Issues"
      },
      {
       "expr": "(sum(ComplianceAsCode_content_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_unassigned_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"}))",
       "legendFormat": "Assigned Issues"
      }
     ]
    },
    {
     "title": "Issues Activity",
     "type": "piechart",
     "description": "This pie chat shows the distribution of Active and Inactive Issues, which are Issues without updates within the last 15 days.\n\nIn general it is not good to have Inactive Issues in the project. Maintainers should check them. It is possible that a contributor or customer is waiting for a feedback or a decision from a maintainer.",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ComplianceAsCode_content_open_issues_count{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_old_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"}))",
       "legendFormat": "Active Issues"
      },
      {
       "expr": "sum(ComplianceAsCode_content_old_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"})",
       "legendFormat": "Inactive Issues"
      }
     ]
    },
    {
     "title": "Team Issues Activity",
     "type": "piechart",
     "description": "This pie chat shows the distribution of Active and Inactive Issues filed by Team members. Inactive Issues are those without updates within the last 15 days.\n\nPing a colleague if your Issue is too long waiting a feedback. If you have an inactive Issue, consider to close it or to provide a short update about your plans to work on it.",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ComplianceAsCode_content_open_issues_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_old_open_issues_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"}))",
       "legendFormat": "Active Issues"
      },
      {
       "expr": "sum(ComplianceAsCode_content_old_open_issues_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"})",
       "legendFormat": "Inactive Issues"
      }
     ]
    },
    {
     "title": "Issues Source",
     "type": "piechart",
     "description": "This pie chart shows how the Open Issues are distributed based on authors.\n\nThese metrics are good to better understand how balanced are the collaboration in the project. But they should not be analysed alone.",
     "gridPos": { "h": 10, "w": 3, "x": 20, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"})",
       "legendFormat": "Team"
      },
      {
       "expr": "(sum(ComplianceAsCode_content_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_open_issues_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"}))",
       "legendFormat": "Community"
      }
     ]
    },
    {
     "title": "Issues Lifetime Average",
     "type": "timeseries",
     "description": "This chart shows the lifetime average of Open Issues but also provides the same metric for closed Issues within the last 30 and 90 days.\n\nIt is usually not good when the Open Issues lifetime average increases. It may indicate that more attention is needed from maintainers in order to review and resolve open Issues.\n\nIt is good to compare the lifetime of Open Issues with closed Issues within the last 30 and 90 days to find patterns and trends. Ideally, the three metrics should have similar and small values.",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_lifetime_average{exported_job=~\".*\"})",
       "legendFormat": "Open Issues"
      },
      {
       "expr": "sum(ComplianceAsCode_content_closed_issues_lifetime_average_30days{exported_job=~\".*\"})",
       "legendFormat": "Closed Issues (30d)"
      },
      {
       "expr": "sum(ComplianceAsCode_content_closed_issues_lifetime_average_90days{exported_job=~\".*\"})",
       "legendFormat": "Closed Issues (90d)"
      }
     ]
    },
    {
     "title": "Issues Assigning Rate",
     "type": "piechart",
     "description": "This pie chat shows the distribution of Assigned and Unassigned Issues.\n\nIn general it is not good to have many Unassigned Issues in the project. Maintainers should assign themselves to Unassigned Issues or delegate an assignee to better investigate the Issue.\n\nIf you are not comfortable to assign the Issue for yourself or delegate an assignee, you can still help by triaging the Issue and including proper labels. It will make it easier to other maintainers to collaborate.",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ComplianceAsCode_content_open_issues_count{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_unassigned_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"}))",
       "legendFormat": "Assigned"
      },
      {
       "expr": "sum(ComplianceAsCode_content_unassigned_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"})",
       "legendFormat": "Unassigned"
      }
     ]
    },
    {
     "title": "Team Issues Assigning Rate",
     "type": "piechart",
     "description": "This pie chat shows the distribution of Assigned and Unassigned Issues.\n\nIn general it is not good to have many Unassigned Issues in the project. Maintainers should assign themselves to Unassigned Issues or delegate an assignee to better investigate the Issue.\n\nIf you are not comfortable to assign the Issue for yourself or delegate an assignee, you can still help by triaging the Issue and including proper labels. It will make it easier to other maintainers to collaborate.",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ComplianceAsCode_content_open_issues_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_unassigned_open_issues_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"}))",
       "legendFormat": "Assigned"
      },
      {
       "expr": "sum(ComplianceAsCode_content_unassigned_open_issues_team{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"})",
       "legendFormat": "Unassigned"
      }
     ]
    },
    {
     "title": "Productization Issues History",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue{exported_job=~\".*\"})",
       "legendFormat": "All Issues"
      },
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_unassigned{exported_job=~\".*\"})",
       "legendFormat": "Unassigned"
      },
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_old{exported_job=~\".*\"})",
       "legendFormat": "Outdated"
      },
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_label_blocked{exported_job=~\".*\"})",
       "legendFormat": "Blocked Issues"
      }
     ]
    },
    {
     "title": "Productization Issues Activity",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_productizationissue_old{exported_job=~\".*\"})",
       "legendFormat": "Active Issues"
      },
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_old{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_blocked{exported_job=~\".*\"})",
       "legendFormat": "Inactive Issues"
      },
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_label_blocked{exported_job=~\".*\"})",
       "legendFormat": "Blocked Issues"
      }
     ]
    },
    {
     "title": "Productization Issues Assigning Rate",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_productizationissue_unassigned{exported_job=~\".*\"})",
       "legendFormat": "Assigned"
      },
      {
       "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_unassigned{exported_job=~\".*\"})",
       "legendFormat": "Unassigned"
      }
     ]
    }
   ]
  },
  { "title": "PRs and Issues Balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "PRs Balance Last 30 Days",
   "type": "timeseries",
   "description": "This chart shows the proportion of PRs created and closed in the last 30 days.\n\nIt is interesting to identify trends. If the difference in Created PRs is positive, it could indicate that project activity is increasing and this is likely related to a relevant context, such as a Benchmark update, new contributors, a team task force, etc.\n\nIt is also interesting to identify necessary actions. For example, if the average Closed PRs is lower than the Created PRs for a long time, maintainers should take actions to change this. Ideally, the Created and Closed means should be equal.",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_created_pulls_30days{exported_job=~\".*\"})",
     "legendFormat": "Created PRs (30d)"
    },
    {
     "expr": "sum(ComplianceAsCode_content_closed_pulls_30days{exported_job=~\".*\"})",
     "legendFormat": "Closed PRs (30d)"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "This status represents the result of the number of PRs created minus the number of PRs closed in 30 days.\n\n- A negative result is Great.\n- A positive result up to 5 is OK.\n- A positive result higher than 5 is Not Good.",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_created_pulls_30days{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_closed_pulls_30days{exported_job=~\".*\"})"
    }
   ]
  },
  {
   "title": "Creation Trend",
   "type": "stat",
   "description": "This trend is defined based on the difference of  result of the number of PRs created minus the number of PRs closed in 30 days.\n\n- A negative result means it is Getting Better.\n- A positive result up to 3 means it is Stable.\n- A positive result higher than 3 means it is Getting Worse.",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_created_pulls_30days{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closing Trend",
   "type": "stat",
   "description": "This trend is defined based on the difference of  result of the number of PRs created minus the number of PRs closed in 30 days.\n\n- A positive result higher than 3 means it is Getting Better.\n- A positive result up to 3 means it is Stable.\n- A negative result means it is Getting Worse.",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_closed_pulls_30days{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PRs Balance Last 90 Days",
   "type": "timeseries",
   "description": "This chart shows the proportion of PRs created and closed in the last 90 days.\n\nIt is interesting to identify trends. If the difference in Created PRs is positive, it could indicate that project activity is increasing and this is likely related to a relevant context, such as a Benchmark update, new contributors, a team task force, etc.\n\nIt is also interesting to identify necessary actions. For example, if the average Closed PRs is lower than the Created PRs for a long time, maintainers should take actions to change this. Ideally, the Created and Closed means should be equal.",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_created_pulls_90days{exported_job=~\".*\"})",
     "legendFormat": "Created PRs (90d)"
    },
    {
     "expr": "sum(ComplianceAsCode_content_closed_pulls_90days{exported_job=~\".*\"})",
     "legendFormat": "Closed PRs (90d)"
    }
   ]
  },
  {
   "title": "Issues Balance Last 30 Days",
   "type": "timeseries",
   "description": "This chart shows the proportion of Issues created and closed in the last 30 days.\n\nIt is interesting to identify trends. If the difference in Created Issues is positive, it could indicate that some recent change had side effects or better quality tests were implemented.\n\nIt is also interesting to identify necessary actions. For example, if the average Closed Issues is lower than the Created Issues for a long time, maintainers should take actions to change this. Ideally, the Created and Closed means should be equal.",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_created_issues_30days{exported_job=~\".*\"})",
     "legendFormat": "Created Issues (30d)"
    },
    {
     "expr": "sum(ComplianceAsCode_content_closed_issues_30days{exported_job=~\".*\"})",
     "legendFormat": "Closed Issues (30d)"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "This status represents the result of the number of Issues created minus the number of Issues closed in 30 days.\n\n- A negative result is Great.\n- A positive result up to 5 is OK.\n- A positive result higher than 5 is Not Good.",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_created_issues_30days{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_closed_issues_30days{exported_job=~\".*\"})"
    }
   ]
  },
  {
   "title": "Creation Trend",
   "type": "stat",
   "description": "This trend is defined based on the difference of  result of the number of Issues created minus the number of Issues closed in 30 days.\n\n- A negative result means it is Getting Better.\n- A positive result up to 3 means it is Stable.\n- A positive result higher than 3 means it is Getting Worse.",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_created_issues_30days{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closing Trend",
   "type": "stat",
   "description": "This trend is defined based on the difference of  result of the number of Issues created minus the number of Issues closed in 30 days.\n\n- A positive result higher than 3 means it is Getting Better.\n- A positive result up to 3 means it is Stable.\n- A negative result means it is Getting Worse.",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_closed_issues_30days{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issues Balance Last 90 Days",
   "type": "timeseries",
   "description": "This chart shows the proportion of Issues created and closed in the last 90 days.\n\nIt is interesting to identify trends. If the difference in Created Issues is positive, it could indicate that some recent change had side effects or better quality tests were implemented.\n\nIt is also interesting to identify necessary actions. For example, if the average Closed Issues is lower than the Created Issues for a long time, maintainers should take actions to change this. Ideally, the Created and Closed means should be equal.",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_created_issues_90days{exported_job=~\".*\"})",
     "legendFormat": "Created Issues (90d)"
    },
    {
     "expr": "sum(ComplianceAsCode_content_closed_issues_90days{exported_job=~\".*\"})",
     "legendFormat": "Closed Issues (90d)"
    }
   ]
  },
  { "title": "Information Based on Labels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "PRs by Products",
   "type": "piechart",
   "description": "This pie chat shows the distribution of Open PRs related to specific Products.\n\nThese metrics are interesting to have some idea about activity related to specific products. Peaks might indicate benchmark updates, new profiles, new products, etc.\n\nIt is always good to investigate the context of peaks. It is common to find opportunities of collaboration among different products regarding coverage.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_rhel7{exported_job=~\".*\"})",
     "legendFormat": "RHEL7"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_rhel8{exported_job=~\".*\"})",
     "legendFormat": "RHEL8"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_rhel9{exported_job=~\".*\"})",
     "legendFormat": "RHEL9"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_sles{exported_job=~\".*\"})",
     "legendFormat": "SLES"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_oraclelinux{exported_job=~\".*\"})",
     "legendFormat": "Oracle"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_ubuntu{exported_job=~\".*\"})",
     "legendFormat": "Ubuntu"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_openshift{exported_job=~\".*\"})",
     "legendFormat": "OpenShift"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_rhel{exported_job=~\".*\"})",
     "legendFormat": "RHEL"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - (sum(ComplianceAsCode_content_open_pulls_label_rhel{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_rhel7{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_rhel8{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_rhel9{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_openshift{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_sles{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_oraclelinux{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_ubuntu{exported_job=~\".*\"}))",
     "legendFormat": "Unclassified"
    }
   ]
  },
  {
   "title": "History of PRs by Products",
   "type": "timeseries",
   "description": "This chat shows the distribution history of Open PRs related to specific Products.\n\nThese metrics are interesting to have some idea about activity related to specific products. Peaks might indicate benchmark updates, new profiles, new products, etc.\n\nIt is always good to investigate the context of peaks. It is common to find opportunities of collaboration among different products regarding coverage. This history can also reveal similarities among products.",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_rhel7{exported_job=~\".*\"})",
     "legendFormat": "RHEL7"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_rhel8{exported_job=~\".*\"})",
     "legendFormat": "RHEL8"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_rhel9{exported_job=~\".*\"})",
     "legendFormat": "RHEL9"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_sles{exported_job=~\".*\"})",
     "legendFormat": "SLES"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_oraclelinux{exported_job=~\".*\"})",
     "legendFormat": "Oracle"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_ubuntu{exported_job=~\".*\"})",
     "legendFormat": "Ubuntu"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_openshift{exported_job=~\".*\"})",
     "legendFormat": "OpenShift"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_rhel{exported_job=~\".*\"})",
     "legendFormat": "RHEL"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - (sum(ComplianceAsCode_content_open_pulls_label_rhel{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_rhel7{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_rhel8{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_rhel9{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_openshift{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_sles{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_oraclelinux{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_ubuntu{exported_job=~\".*\"}))",
     "legendFormat": "Unclassified"
    }
   ]
  },
  {
   "title": "Other Relevant Labels",
   "type": "timeseries",
   "description": "This chart shows the history of PRs and Issues based on some relevant labels.\n\nThe numbers include both Issues and PRs.\n\nThese metrics are interesting to identify patterns and peaks of specific Issues or PRs.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue{exported_job=~\".*\"})",
     "legendFormat": "productization-issue"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_bugfix{exported_job=~\".*\"})",
     "legendFormat": "bugfix"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_blocker{exported_job=~\".*\"})",
     "legendFormat": "blocker"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_highlight{exported_job=~\".*\"})",
     "legendFormat": "highlight"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_blocked{exported_job=~\".*\"})",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "PRs by Standards",
   "type": "piechart",
   "description": "This pie chat shows the distribution of Open PRs related to specific Standards.\n\nThese metrics are interesting to have some idea about activity related to specific standards. Peaks might indicate benchmark updates, new profiles, new rules, etc.\n\nIt is always good to investigate the context of peaks. It is common to find opportunities of collaboration among different products regarding standards coverage.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_anssi{exported_job=~\".*\"})",
     "legendFormat": "ANSSI"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_ccn{exported_job=~\".*\"})",
     "legendFormat": "CCN"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_cis{exported_job=~\".*\"})",
     "legendFormat": "CIS"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_ospp{exported_job=~\".*\"})",
     "legendFormat": "OSPP"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_pcidss{exported_job=~\".*\"})",
     "legendFormat": "PCI-DSS"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_stig{exported_job=~\".*\"})",
     "legendFormat": "STIG"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - (sum(ComplianceAsCode_content_open_pulls_label_anssi{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_ccn{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_cis{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_ospp{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_pcidss{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_stig{exported_job=~\".*\"}))",
     "legendFormat": "Unclassified"
    }
   ]
  },
  {
   "title": "History of PRs by Standards",
   "type": "timeseries",
   "description": "This chat shows the distribution history of Open PRs related to specific Standards.\n\nThese metrics are interesting to have some idea about activity related to specific standards. Peaks might indicate benchmark updates, new profiles, new rules, etc.\n\nIt is always good to investigate the context of peaks. It is common to find opportunities of collaboration among different products regarding standards coverage.",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 31 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_anssi{exported_job=~\".*\"})",
     "legendFormat": "ANSSI"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_ccn{exported_job=~\".*\"})",
     "legendFormat": "CCN"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_cis{exported_job=~\".*\"})",
     "legendFormat": "CIS"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_ospp{exported_job=~\".*\"})",
     "legendFormat": "OSPP"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_pcidss{exported_job=~\".*\"})",
     "legendFormat": "PCI-DSS"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_label_stig{exported_job=~\".*\"})",
     "legendFormat": "STIG"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - (sum(ComplianceAsCode_content_open_pulls_label_anssi{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_ccn{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_cis{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_ospp{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_pcidss{exported_job=~\".*\"}) + sum(ComplianceAsCode_content_open_pulls_label_stig{exported_job=~\".*\"}))",
     "legendFormat": "Unclassified"
    }
   ]
  },
  {
   "title": "History of Check and Remediation",
   "type": "timeseries",
   "description": "This chart shows the history of PRs and Issues based on some relevant labels.\n\nThe numbers include both Issues and PRs.\n\nThese metrics are interesting to identify patterns and peaks of specific Issues or PRs.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_ansible{exported_job=~\".*\"})",
     "legendFormat": "Ansible"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_bash{exported_job=~\".*\"})",
     "legendFormat": "Bash"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_oval{exported_job=~\".*\"})",
     "legendFormat": "OVAL"
    }
   ]
  }
 ]
}