{
 "title": "Content_Workflows",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Monitored Workflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nightly Builds Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_workflow_NightlybuildswithOVAL511_conclusion_status{exported_job=~\".*\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "GitHub Pages Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_workflow_GithubPages_conclusion_status{exported_job=~\".*\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Gate Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_workflow_Gate_conclusion_status{exported_job=~\".*\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Workflows Duration History",
   "type": "timeseries",
   "description": "This graph shows the duration of executions of monitored Workflows.\n\nDuration history is interesting to detect any discrepancies in duration time. Discrepancies may suggest infrastructure issues, relevant changes, etc.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_workflow_NightlybuildswithOVAL511_duration_seconds{exported_job=~\".*\"})",
     "legendFormat": "Nightly Build"
    },
    {
     "expr": "sum(ComplianceAsCode_content_workflow_GithubPages_duration_seconds{exported_job=~\".*\"})",
     "legendFormat": "GitHub Pages"
    },
    {
     "expr": "sum(ComplianceAsCode_content_workflow_Gate_duration_seconds{exported_job=~\".*\"})",
     "legendFormat": "Gate"
    }
   ]
  },
  {
   "title": "Nightly Builds Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_workflow_NightlybuildswithOVAL511_duration_seconds{exported_job=~\".*\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "GitHub Pages Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_workflow_GithubPages_duration_seconds{exported_job=~\".*\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Gate Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_workflow_Gate_duration_seconds{exported_job=~\".*\"})",
     "legendFormat": "Status"
    }
   ]
  },
  { "title": "Content Workflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Workflows Capacity Plan",
   "type": "timeseries",
   "description": "This chart shows the number not Completed jobs. It means any Job which is in execution or waiting to be executed.",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_workflows_status{status=\"in_progress\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ComplianceAsCode_content_workflows_status{status=\"queued\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ComplianceAsCode_content_workflows_status{status=\"action_required\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ComplianceAsCode_content_workflows_status{status=\"waiting\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ComplianceAsCode_content_workflows_status{status=\"stale\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Runs Status",
   "type": "timeseries",
   "description": "This chart shows the number of Workflows Runs for each possible status.",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_workflows_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "piechart",
   "description": "This chart shows the number of Workflows Runs for each possible status.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_workflows_status{status=\"success\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ComplianceAsCode_content_workflows_status{status=\"failure\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ComplianceAsCode_content_workflows_status{status=\"cancelled\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Limits Hits",
   "type": "timeseries",
   "description": "This chart shows the number of \"in_progress\" Workflows Runs and includes a reference for the limits in each GitHub Plan.\n\nIt is interesting to know how often the current plan is hitting the Jobs limits.\n\n- Free: 20\n- Pro: 40\n- Team: 60\n- Enterprise: 500",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 13 },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_workflows_status{status=\"in_progress\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}