{
 "title": "Team_Meeting",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "PRs Status and Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open PRs Summary",
   "type": "timeseries",
   "description": "This chart shows the main metrics about Open PRs.\n\nWhen comparing the numbers within an interval it is interesting to check the \"Difference\" value. Negative values are usually good and mean the queue is getting smaller in the specific interval. Positive values may indicate that PRs are taking too long to be reviewed and merged or the community is getting more active.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Open PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Unassigned PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Outdated PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Draft PRs"
    }
   ]
  },
  {
   "title": "Queue Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the queue is Getting Smaller.\n- A positive result up to 3 means the queue is Stable.\n- A positive result higher than 3 means the queue is Getting Bigger.",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Draft Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the number of draft items is Getting Smaller.\n- A positive result up to 3 means the number of draft items is Stable.\n- A positive result higher than 3 means the number of draft items is Getting Bigger.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PRs Activity",
   "type": "piechart",
   "description": "This pie chat shows the distribution of Active and Inactive PRs, which are PRs without updates within the last 15 days.\n\nIn general it is not good to have Inactive PRs in the project. Maintainers should check them. It is possible that a contributor is waiting for a feedback or an unsolved discussion needs intervention and final decision from a maintainer.\n\nThe Draft PRs are not considered Inactive PRs in this context because they are usually expected to be outdated. It is a common practice that authors set their PRs to draft when something is still pending but the author does not expected to work on it soon.",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"}))",
     "legendFormat": "Active PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Inactive PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Draft PRs"
    }
   ]
  },
  {
   "title": "PRs Source",
   "type": "piechart",
   "description": "This pie chart shows how the Open PRs are distributed based on authors.\n\nThese metrics are good to better understand how balanced are the collaboration in the project. But they should not be analysed alone.\n\nIn general, all team members are also project maintainers. So it is natural to have more collaboration among team members reflecting in better quality code and consequently faster reviews. Therefore, it is expected that most of the Open PRs comes from the Community.\n\nThese number can be better contextualized by analyzing the other charts, specially the ones about Products and Standards distribuition.",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"})",
     "legendFormat": "Team"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls_team{exported_job=~\".*\"})",
     "legendFormat": "Community"
    }
   ]
  },
  {
   "title": "Assignment Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the assignment rate is Getting Better.\n- A positive result up to 3 means the assignment rate is Stable.\n- A positive result higher than 3 means the assignment rate is Getting Worse.",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outdated Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the number of outdated items is Getting Better.\n- A positive result up to 3 means the number of outdated items is Stable.\n- A positive result higher than 3 means the number of outdated items is Getting Worse.",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PRs Lifetime Average",
   "type": "timeseries",
   "description": "This chart shows the lifetime average of Open PRs but also provides the same metric for closed PRs within the last 30 and 90 days.\n\nIt is usually not good when the Open PRs lifetime average increases. It may indicate that more attention is needed from maintainers in order to review open PRs and allow the authors to move forward. The context should be clarified.\n\nIt is good to compare the lifetime of Open PRs with closed PRs within the last 30 and 90 days to find patterns and trends. Ideally, the three metrics should have similar and small values.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_lifetime_average{exported_job=~\".*\"})",
     "legendFormat": "Open PRs"
    },
    {
     "expr": "sum(ComplianceAsCode_content_closed_pulls_lifetime_average_30days{exported_job=~\".*\"})",
     "legendFormat": "Closed PRs (30d)"
    },
    {
     "expr": "sum(ComplianceAsCode_content_closed_pulls_lifetime_average_90days{exported_job=~\".*\"})",
     "legendFormat": "Closed PRs (90d)"
    }
   ]
  },
  {
   "title": "Open PRs Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the Open PRs resolutions are Taking Longer.\n- A positive result up to 3 means the Open PRs resolutions are Stable.\n- A positive result higher than 3 means the Open PRs resolutions are Getting Faster.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_pulls_lifetime_average{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PRs Assigning Rate",
   "type": "piechart",
   "description": "This pie chat shows the distribution of Assigned and Unassigned PRs, except for Draft PRs.\n\nIn general it is not good to have many Unassigned PRs in the project. Maintainers should assign themselves to Unassigned PRs or delegate an assignee to review and allow the PR to move forward.\n\nIf you are not comfortable to assign the PR for yourself or delegate an assignee, you can still help by triaging the PR and including proper labels. It will make it easier to other maintainers to collaborate.\n\nThe Draft PRs are not considered Inactive PRs in this context because they are usually not expecting reviews.",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"}))",
     "legendFormat": "Assigned"
    },
    {
     "expr": "sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Unassigned"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_donotmerge_workinprogress{exported_job=~\".*\"})",
     "legendFormat": "Draft PRs"
    }
   ]
  },
  {
   "title": "Productization Issues Status and Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Productization Issues History",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue{exported_job=~\".*\"})",
     "legendFormat": "All Issues"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_unassigned{exported_job=~\".*\"})",
     "legendFormat": "Unassigned"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_old{exported_job=~\".*\"})",
     "legendFormat": "Outdated"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_blocked{exported_job=~\".*\"})",
     "legendFormat": "Blocked Issues"
    }
   ]
  },
  {
   "title": "Issues Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the issues are Reducing.\n- A positive result up to 2 means the number of issues is Stable.\n- A positive result higher than 2 means the issues are Increasing.",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the number of blocked items is Getting Smaller.\n- A positive result up to 2 means the number of blocked items is Stable.\n- A positive result higher than 2 means the number of blocked items is Getting Bigger.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_blocked{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Productization Issues Activity",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_productizationissue_old{exported_job=~\".*\"})",
     "legendFormat": "Active Issues"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_old{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_blocked{exported_job=~\".*\"})",
     "legendFormat": "Inactive Issues"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_blocked{exported_job=~\".*\"})",
     "legendFormat": "Blocked Issues"
    }
   ]
  },
  {
   "title": "Unblocked Issues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_blocked{exported_job=~\".*\"})"
    }
   ]
  },
  {
   "title": "Assignment Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the assignment rate is Getting Better.\n- A positive result up to 2 means the assignment rate is Stable.\n- A positive result higher than 2 means the assignment rate is Getting Worse.",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_unassigned{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outdated Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the number of outdated items is Getting Better.\n- A positive result up to 2 means the number of outdated items is Stable.\n- A positive result higher than 2 means the number of outdated items is Getting Worse.",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_old{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Productization Issues Assigning Rate",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_issues_label_productizationissue_unassigned{exported_job=~\".*\"})",
     "legendFormat": "Assigned"
    },
    {
     "expr": "sum(ComplianceAsCode_content_open_issues_label_productizationissue_unassigned{exported_job=~\".*\"})",
     "legendFormat": "Unassigned"
    }
   ]
  },
  { "title": "All Issues Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Open Issues Summary",
   "type": "timeseries",
   "description": "This chart shows the main metrics about Open Issues.\n\nWhen comparing the numbers within an interval it is interesting to check the \"Difference\" value. Negative values are usually good and mean the queue is getting smaller in the specific interval. Positive values may indicate that Issues are taking too long to be reviewed and resolved.\n\nPeaks might also indicate more serious issues in a specific release or profile.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Open Issues"
    },
    {
     "expr": "sum(ComplianceAsCode_content_unassigned_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Unassigned Issues"
    },
    {
     "expr": "sum(ComplianceAsCode_content_old_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Outdated Issues"
    },
    {
     "expr": "(sum(ComplianceAsCode_content_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_unassigned_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"}))",
     "legendFormat": "Assigned Issues"
    }
   ]
  },
  {
   "title": "Issues Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the issues are Reducing.\n- A positive result up to 2 means the number of issues is Stable.\n- A positive result higher than 2 means the issues are Increasing.",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outdated Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the number of outdated items is Getting Better.\n- A positive result up to 2 means the number of outdated items is Stable.\n- A positive result higher than 2 means the number of outdated items is Getting Worse.",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_old_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issues Activity",
   "type": "piechart",
   "description": "This pie chat shows the distribution of Active and Inactive Issues, which are Issues without updates within the last 15 days.\n\nIn general it is not good to have Inactive Issues in the project. Maintainers should check them. It is possible that a contributor or customer is waiting for a feedback or a decision from a maintainer.",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(ComplianceAsCode_content_open_issues_count{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_open_pulls{exported_job=~\".*\"})) - (sum(ComplianceAsCode_content_old_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"}))",
     "legendFormat": "Active Issues"
    },
    {
     "expr": "sum(ComplianceAsCode_content_old_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_old_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "Inactive Issues"
    }
   ]
  },
  {
   "title": "Assignment Trend",
   "type": "stat",
   "description": "This trend is defined based on the result difference between the first and last values in the selected interval.\n\n- A negative result means the assignment rate is Getting Better.\n- A positive result up to 2 means the assignment rate is Stable.\n- A positive result higher than 2 means the assignment rate is Getting Worse.",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ComplianceAsCode_content_unassigned_open_issues{exported_job=~\".*\"}) - sum(ComplianceAsCode_content_unassigned_open_pulls{exported_job=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}