version: '3.5'

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus/conf/:/etc/prometheus/:Z
      - ./prometheus/data/:/prometheus/:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      #- '--web.console.libraries=/etc/prometheus/console_libraries'
      #- '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=5y'
      - '--web.enable-lifecycle'
      #- '--web.enable-admin-api'
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - mbcm_net_frontend

  pushgateway:
    image: prom/pushgateway:latest
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - mbcm_net_frontend

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
        - ./gfn_env/provisioning:/etc/grafana/provisioning:Z
        - ./gfn_env/dashboards:/var/lib/grafana/dashboards:Z
        - ./logs/grafana/:/var/log/grafana:Z
    env_file:
    - .env_grafana
    secrets:
    - GRAFANA_ADMIN_PASSWORD
    networks:
      - mbcm_net_frontend

networks:
  mbcm_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24

secrets:
  GRAFANA_ADMIN_PASSWORD:
    file: ./.GRAFANA_ADMIN_PASSWORD
