global:
  scrape_interval:     15m
  scrape_timeout:      1m

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'community-mon'

scrape_configs:
  - job_name: 'CommunityMon'
    scrape_interval: 15m
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'ComplianceAsCode_Policies'
    scrape_interval: 15m
    scheme: https
    metrics_path: '/content-pages/prometheus_stats/policies_metrics'
    static_configs:
      - targets: ['complianceascode.github.io']
